title: <p align="center"> Piyali Podder </p>
<h1 align="center">Hi ğŸ‘‹, I'm Piyali Podder</h1>
logo: /assets/img/Piyali 2.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/piyali-podder-610b78175">LinkedIn</a> |
  <a href="https://github.com/PiyaP-lab/">GitHub</a>
  
  <br>
   - ğŸ‘¨â€ğŸ’» I'm working on Automation Testing projects along with DataScience and AI/ML projects as a part of GEN-AI Practice 
   - ğŸŒ± Iâ€™m currently exploring about **RAG applications & Applied LLMs** 
   - ğŸ“« How to reach me **piyali.podder89@outlook.com**
  </br>
  
  </p>



theme: jekyll-theme-minimal
