title: "Piyali Podder"
logo: /assets/img/Piyali_2.png

description: 
  <p align="center">
    <a href="/Piyali_Podder_Portfolio/pdf/PiyaliPodderResume.pdf" target="_blank">Resume</a> 
    <a href="https://www.linkedin.com/in/piyali-podder-610b78175">LinkedIn</a> |
    <a href="https://github.com/PiyaP-lab/">GitHub</a>
    <br><br>
    ğŸ‘©â€ğŸ’» I'm working on Automation Testing projects along with Data Science and AI/ML projects as part of the GEN-AI Practice. <br>
    ğŸŒ± Iâ€™m currently exploring <strong>RAG applications</strong> & <strong>Applied LLMs</strong>. <br>
    ğŸ“« Reach me at <strong>piyali.podder89@outlook.com</strong>.
  </p>

theme: jekyll-theme-minimal

